server {
    listen 80;
    server_name 13.222.110.63;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias /home/allyan/Documents/Blogging_Platform/blogging_platform/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/allyan/Documents/Blogging_Platform/blogging_platform/blogproject.sock;
    }
}
